version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # jobs are calles later in the workflows sections
jobs:
  Automate_build_deploy:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:14.15"
    steps:
      # install node and checkout code
      - node/install:
          node-version: '14.15'  
      - eb/setup
      - aws-cli/setup       
      - checkout
      # Show the node version
      - run:
          name: Show the node version
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
     # Install dependencies in the the backend API          
      # - run:
      #     name: Install API Dependencies
      #     command: |
      #       echo "Install dependencies in the the backend API  "
      #       npm run api:install
      # # test the backend API      
      # - run:
      #     name: API Test
      #     command: |
      #       echo "test the backend API"
      #       npm run api:test
      # # Build the backend API      
      # - run:
      #     name: API Build
      #     command: |
      #       echo "Build the backend API"
      #       npm run api:build
      # # Deploy the backend API      
      # - run:
      #     name: API Deploy
      #     command: |
      #       echo "Deploy the backend API"
      #       npm run api:deploy

            # npm cache clean --force
            # rm -rf package-lock.json
    # install dependencies in the frontend app
      - run:
          name: Install Frontend Dependencies
          command: |
            npm run frontend:install
      # Build the frontend app
      - run:
          name: Frontend Build
          command: |
            echo "Build the frontend app"
            npm run frontend:build
      # # Deploy the frontend app         
      # - run:
      #     name: Frontend Deploy
      #     command: |
      #       echo "Build the frontend app"
      #       npm run frontend:deploy
          
workflows:
  udagram:
    jobs:
      - Automate_build_deploy
